{"name": "test_create_two_similar_courier_and_couriers_with_the_same_login_impossible", "status": "failed", "statusDetails": {"message": "AssertionError: Result is 409 but code is 409 and text is {\"code\":409,\"message\":\"Этот логин уже используется. Попробуйте другой.\"}, but text have to be = \"message\": \"Этот логин уже используется\"\nassert (409 == 409 and '{\"code\":409,...йте другой.\"}' == '{\"message\": ...спользуется\"}'\n  \n  - {\"message\": \"Этот логин уже используется\"}\n  + {\"code\":409,\"message\":\"Этот логин уже используется. Попробуйте другой.\"})", "trace": "self = <tests.test_courier_creation.TestCourierCreation object at 0x000001FC9C3D6C30>\n\n    def test_create_two_similar_courier_and_couriers_with_the_same_login_impossible(self):\n        payload = {\"login\": data.login, \"password\": data.password, \"firstName\": data.first_name}\n        requests.post('https://qa-scooter.praktikum-services.ru/api/v1/courier', data=payload)\n        response_second = requests.post('https://qa-scooter.praktikum-services.ru/api/v1/courier', data=payload)\n        code_response = response_second.status_code\n        text_response = response_second.text\n        courier_payload = {\"login\": payload[\"login\"], \"password\": payload[\"password\"]}\n        courier_login = requests.post('https://qa-scooter.praktikum-services.ru/api/v1/courier/login',\n                                      data=courier_payload)\n        cl = courier_login.json()\n        courier_id = cl[\"id\"]\n        del_payload = {\"id\": courier_id}\n        requests.delete(f'https://qa-scooter.praktikum-services.ru/api/v1/courier/{courier_id}',\n                        data=del_payload)\n>       assert code_response == 409 and text_response == '{\"message\": \"Этот логин уже используется\"}', (\n            f'Result is {code_response} but code is 409'\n            f' and text is {text_response}, but text have to be = \"message\": \"Этот логин уже используется\"'\n        )\nE       AssertionError: Result is 409 but code is 409 and text is {\"code\":409,\"message\":\"Этот логин уже используется. Попробуйте другой.\"}, but text have to be = \"message\": \"Этот логин уже используется\"\nE       assert (409 == 409 and '{\"code\":409,...йте другой.\"}' == '{\"message\": ...спользуется\"}'\nE         \nE         - {\"message\": \"Этот логин уже используется\"}\nE         + {\"code\":409,\"message\":\"Этот логин уже используется. Попробуйте другой.\"})\n\ntests\\test_courier_creation.py:39: AssertionError"}, "start": 1710021598443, "stop": 1710021600451, "uuid": "1bf92571-aeb3-463d-9fc4-0f90f3c29478", "historyId": "ba5a7a5cbe296c59f063316b576c6cab", "testCaseId": "ba5a7a5cbe296c59f063316b576c6cab", "fullName": "tests.test_courier_creation.TestCourierCreation#test_create_two_similar_courier_and_couriers_with_the_same_login_impossible", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_creation"}, {"name": "subSuite", "value": "TestCourierCreation"}, {"name": "host", "value": "Glavnyi-PC"}, {"name": "thread", "value": "28976-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_creation"}]}